# Generated by Django 3.1.3 on 2020-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_usermodel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
