# Generated by Django 3.1.3 on 2020-12-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_usermodel_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='friends',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friends',
            field=models.ManyToManyField(related_name='_usermodel_friends_+', to='base.UserModel'),
        ),
    ]
