# Generated by Django 3.1.3 on 2020-12-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201201_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_usermodel_friends_+', to='base.UserModel'),
        ),
    ]
